name: Build and publish plugin JAR

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify phase
        run: mvn -Drevision=${{github.ref_name}} --batch-mode --update-snapshots verify package
      - name: Attach the JAR to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: target/tg-bridge-${{github.ref_name}}.jar
